services:
    varnish:
        labels:
            - traefik.enable=true
            # Serve magento over http
            - traefik.http.routers.${PROJECT_NAME?PROJECT_NAME must be set.}-magento-http.rule=Host(`$PROJECT_NAME.docker.localhost`)
            - traefik.http.routers.$PROJECT_NAME-magento-http.entrypoints=http
            # Serve magento over https
            - traefik.http.routers.$PROJECT_NAME-magento-https.rule=Host(`$PROJECT_NAME.docker.localhost`)
            - traefik.http.routers.$PROJECT_NAME-magento-https.entrypoints=https
            - traefik.http.routers.$PROJECT_NAME-magento-https.tls=true
        volumes:
            - ./docker/conf/varnish/default-dev.vcl:/etc/varnish/default.vcl

    web:
        image: ${PROJECT_NAME?PROJECT_NAME must be set.}_web
        build: ./docker/images/nginx
        depends_on:
            - php_xdebug
        volumes:
            - ${MAGENTO_DIR}:/var/www/html:rw,cached
            - ./docker/conf/nginx/default-dev.conf:/etc/nginx/conf.d/default.conf

    php:
        image: ${PROJECT_NAME?PROJECT_NAME must be set.}_php
        build:
            context: ./docker/images/php
            target: dev
            args:
                PHP_VERSION: ${PHP_VERSION}
                COMPOSER_VERSION: ${COMPOSER_VERSION}
        user: ${DOCKER_UID}:${DOCKER_GID}
        environment:
            COMPOSER_AUTH: ${COMPOSER_AUTH:-}
        volumes:
            - ${MAGENTO_DIR}:/var/www/html:rw,cached
            - composer-cache:/tmp/composer
            - npm-cache:/tmp/npm

    php_xdebug:
        build:
            context: ./docker/images/php
            target: xdebug
            args:
                PHP_VERSION: ${PHP_VERSION}
        user: ${DOCKER_UID}:${DOCKER_GID}
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - ${MAGENTO_DIR}:/var/www/html:rw,cached

    cron:
        image: ${PROJECT_NAME?PROJECT_NAME must be set.}_cron
        build:
            context: ./docker/images/php
            target: base
            args:
                PHP_VERSION: ${PHP_VERSION}
        environment:
            DOCKER_UID: ${DOCKER_UID}
            DOCKER_GID: ${DOCKER_GID}
        volumes:
            - ${MAGENTO_DIR}:/var/www/html:rw,cached

    elasticsearch:
        labels:
            - traefik.enable=true
            - traefik.http.services.${PROJECT_NAME?PROJECT_NAME must be set.}-elastic.loadbalancer.server.port=9200
            # Serve elasticsearch over http
            - traefik.http.routers.$PROJECT_NAME-elastic-http.rule=Host(`elastic.$PROJECT_NAME.docker.localhost`)
            - traefik.http.routers.$PROJECT_NAME-elastic-http.entrypoints=http

    rabbitmq:
        labels:
            - traefik.enable=true
            - traefik.http.services.${PROJECT_NAME?PROJECT_NAME must be set.}-rabbitmq.loadbalancer.server.port=15672
            # Serve rabbitmq over http
            - traefik.http.routers.$PROJECT_NAME-rabbitmq-http.rule=Host(`rabbitmq.$PROJECT_NAME.docker.localhost`)
            - traefik.http.routers.$PROJECT_NAME-rabbitmq-http.entrypoints=http

    maildev:
        labels:
            - traefik.enable=true
            - traefik.http.services.${PROJECT_NAME?PROJECT_NAME must be set.}-maildev.loadbalancer.server.port=1080
            # Serve maildev over http
            - traefik.http.routers.$PROJECT_NAME-maildev-http.rule=Host(`maildev.$PROJECT_NAME.docker.localhost`)
            - traefik.http.routers.$PROJECT_NAME-maildev-http.entrypoints=http

volumes:
    composer-cache:
    npm-cache:
