version: '3.4'

services:
    varnish:
        image: registry.smile.fr/magento2/varnish:$VARNISH_TAG
        ports:
            - 80
        depends_on:
            - web

    web:
        image: registry.smile.fr/magento2/nginx:$NGINX_TAG
        ports:
            - 80
            - 443
            - 8080
        env_file:
            - docker/env/config.env
        depends_on:
            - fpm
        volumes:
            - appdata:/var/www/html

    fpm:
        image: registry.smile.fr/magento2/php:$PHP_FPM_TAG
        ports:
            - 9000
        env_file:
            - docker/env/config.env
        depends_on:
            - db
            - elasticsearch
            - maildev
            - rabbitmq
            - redis
        volumes:
            - appdata:/var/www/html

    cli:
        image: registry.smile.fr/magento2/php:$PHP_CLI_TAG
        env_file:
            - docker/env/config.env
            - .env
        depends_on:
            - db
            - elasticsearch
            - rabbitmq
            - redis
        volumes:
            - appdata:/var/www/html

    cron:
        image: registry.smile.fr/magento2/php:$PHP_CLI_TAG
        command: run-cron
        environment:
            CRONTAB: '* * * * * /usr/local/bin/php /var/www/html/bin/magento cron:run >> /var/www/html/var/log/cron.log'
        env_file:
            - docker/env/config.env
            - .env
        depends_on:
            - db
            - elasticsearch
            - rabbitmq
            - redis
        volumes:
            - appdata:/var/www/html

    db:
        image: mariadb:$MARIADB_TAG
        ports:
            - 3306
        env_file:
            - docker/env/config.env
        healthcheck:
            test: 'mysqladmin ping -h localhost -pmagento2'
            interval: 30s
            timeout: 30s
            retries: 3
        volumes:
            - dbdata:/var/lib/mysql

    elasticsearch:
        image: registry.smile.fr/magento2/elasticsearch:$ELASTICSEARCH_TAG
        ports:
            - 9200
        env_file:
            - docker/env/config.env
        volumes:
            - esdata:/usr/share/elasticsearch/data

    redis:
        image: redis:$REDIS_TAG
        ports:
            - 6379
        healthcheck:
            test: 'redis-cli ping || exit 1'
            interval: 30s
            timeout: 30s
            retries: 3
        volumes:
            - redisdata:/data

    rabbitmq:
        image: rabbitmq:$RABBITMQ_TAG
        ports:
            - 15672
            - 5672
        volumes:
            - rabbitmqdata:/var/lib/rabbitmq
        env_file:
            - docker/env/config.env

    maildev:
        image: maildev/maildev:$MAILDEV_TAG
        ports:
            - 1025
            - 1080

volumes:
    appdata:
    dbdata:
    esdata:
    rabbitmqdata:
    redisdata:
