version: '3.4'

services:
    varnish:
        image: ${VARNISH_IMAGE?VARNISH_IMAGE must be set.}
        ports:
            - 80
        depends_on:
            - web
        volumes:
            - ./docker/conf/varnish/default.vcl:/etc/varnish/default.vcl

    web:
        image: ${NGINX_IMAGE?NGINX_IMAGE must be set.}
        ports:
            - 80
            - 443
            - 8080
        depends_on:
            - php
        volumes:
            - appdata:/var/www/html

    php:
        image: ${PHP_FPM_IMAGE?PHP_FPM_IMAGE must be set.}
        ports:
            - 9000
        env_file:
            - docker/env/php.env
        depends_on:
            - db
            - elasticsearch
            - maildev
            - rabbitmq
            - redis
        volumes:
            - appdata:/var/www/html

    cron:
        image: ${PHP_FPM_IMAGE?PHP_FPM_IMAGE must be set.}
        command: run-cron
        environment:
            CRONTAB: '* * * * * /usr/local/bin/php /var/www/html/bin/magento cron:run >> /var/www/html/var/log/cron.log'
        env_file:
            - docker/env/php.env
        depends_on:
            - db
            - elasticsearch
            - maildev
            - rabbitmq
            - redis
        volumes:
            - appdata:/var/www/html

    db:
        image: ${MYSQL_IMAGE?MYSQL_IMAGE must be set.}
        ports:
            - 3306
        env_file:
            - docker/env/db.env
        healthcheck:
            test: 'mysqladmin ping -h localhost -pmagento2'
            interval: 30s
            timeout: 30s
            retries: 3
        volumes:
            - dbdata:/var/lib/mysql

    elasticsearch:
        image: ${ELASTICSEARCH_IMAGE?ELASTICSEARCH_IMAGE must be set.}
        ports:
            - 9200
        ulimits:
            memlock:
                soft: -1
                hard: -1
        environment:
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
        env_file:
            - docker/env/elasticsearch.env
        volumes:
            - esdata:/usr/share/elasticsearch/data

    redis:
        image: ${REDIS_IMAGE?REDIS_IMAGE must be set.}
        ports:
            - 6379
        healthcheck:
            test: 'redis-cli ping || exit 1'
            interval: 30s
            timeout: 30s
            retries: 3

    rabbitmq:
        image: ${RABBITMQ_IMAGE?RABBITMQ_IMAGE must be set.}
        ports:
            - 15672
            - 5672
        env_file:
            - docker/env/rabbitmq.env
        volumes:
            - rabbitmqdata:/var/lib/rabbitmq

    maildev:
        image: ${MAILDEV_IMAGE?MAILDEV_IMAGE must be set.}
        ports:
            - 1025
            - 1080

volumes:
    appdata:
    dbdata:
    esdata:
    rabbitmqdata:
