version: '3.4'

services:
    web:
        volumes:
            - ./src:/var/www/html:rw,cached

    fpm:
        user: ${DOCKER_UID?$DOCKER_UID must be set.}:${DOCKER_GID?$DOCKER_GID must be set.}
        volumes:
            - ./src:/var/www/html:rw,cached

    cli:
        user: ${DOCKER_UID?$DOCKER_UID must be set.}:${DOCKER_GID?$DOCKER_GID must be set.}
        volumes:
            - ./src:/var/www/html:rw,cached

    cron:
        volumes:
            - ./src:/var/www/html:rw,cached
