before_script:
    - composer install

sniffers:
    stage: test
    tags:
        - php{php_ci_version}
        - ubuntu
    script:
        - bin/magento setup:di:compile
        - vendor/bin/grumphp run --no-interaction
