default:
    image: registry.smile.fr/magento2/php:{{ php_version }}-fpm-dev-1
    tags:
        - galaxy-docker-shared
    cache:
        - key: composer-cache
          paths:
              - .composer-cache/
    before_script:
        - composer config -g cache-dir "$(pwd)/.composer-cache"

code-analysis:
    stage: test
    script:
        - composer install --no-interaction
        - vendor/bin/grumphp run --no-interaction
        - vendor/bin/SmileAnalyser launch --strict --skipNotices yes
