before_script:
    - composer install

sniffers:
    stage: test
    tags:
        - php{php_ci_version}
        - ubuntu
    script:
        - vendor/bin/grumphp run --no-interaction
        - vendor/bin/SmileAnalyser launch --skipNotices yes --output xml --filename smileanalyser.xml && [ -f "smileanalyser.xml" ] && ! cat smileanalyser.xml | grep "<error"; status=$?
        - if [ "$status" -gt 0 ]; then exit "$status"; fi
